import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionProvider from "../components/providers/NextAuthProvider"
import "./globals.css";
import ReactQueryProvider from "@/components/providers/ReactQueryProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <ReactQueryProvider>
          <SessionProvider>
            {children}
          </SessionProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
