import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionProvider from "../components/providers/NextAuthProvider"
import "./globals.css";
import { auth } from "./api/auth/[...nextauth]/route";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const session = await auth()

  return (
    <html lang="pt-br">
      <body className={inter.className}>
        
          <SessionProvider session={session}>
            {children}
          </SessionProvider>

      </body>
    </html>
  );
}
